manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: nickconway
      url-base: https://github.com/nickconway
    - name: ghostbuster91 #new entry
      url-base: https://github.com/ghostbuster91 #new entry

  projects:
    - name: zmk-auto-layer
      remote: urob
      revision: main
      path: modules/auto-layer

    # ZMK with Zephyr namespaced under /zmk. This requires that ZMK imports
    # Zephyr with a path other than `zephyr` (as in `going-modular`).
    # - name: zmk
    #   remote: upstream
    #   revision: main
    #   import: app/west.yml

    - name: zmk
      remote: nickconway
      revision: smart-interrupt
      import: app/west.yml

    - name: nice-view-gem #new entry
      remote: ghostbuster91 #new entry
      revision: main #new entry

  self:
    path: config
